services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://127.0.0.1:80
      - VITE_ASSISTANT_ID=nutribuddy v1.2.1
      - VITE_LANGSMITH_API_KEY=M26v4Y3uLhGu
    restart: always
