version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://127.0.0.1:8123
      - VITE_ASSISTANT_ID=nutribuddy v1.2.1
    stdin_open: true
    tty: true
