FROM node:23-alpine

WORKDIR /app

# Copy package dependencies
COPY package.json package-lock.json* ./
RUN npm install 

# We don't copy the source code here as it will be mounted as a volume

# Expose port (Vite's default)
EXPOSE 5173

# Run development server with host set to 0.0.0.0 to allow external access
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
