services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
        - VITE_API_URL=https://nutri-buddy.ch:8123
        - VITE_ASSISTANT_ID=nutribuddy v1.2.1
        - VITE_LANGSMITH_API_KEY=M26v4Y3uLhGu
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro 
    restart: unless-stopped
    # Optional: add healthcheck
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
